"""cases table

Revision ID: 0c6141f4282c
Revises:
Create Date: 2026-07-12 18:49:58.615942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0c6141f4282c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("case_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("claim_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_stage", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("plaintiff_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "plaintiff_counsel", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("defense_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("defense_counsel", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("court", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("county", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trial_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("analysis", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_case_name"), "cases", ["case_name"], unique=False)
    op.create_index(op.f("ix_cases_user_id"), "cases", ["user_id"], unique=False)
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("claim_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("legal_basis", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("elements", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_case_id"), "claims", ["case_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("chunks_count", sa.Integer(), nullable=False),
        sa.Column(
            "qdrant_document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_filename"), "documents", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_documents_qdrant_document_id"),
        "documents",
        ["qdrant_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False
    )
    op.create_table(
        "extracted_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_document", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("is_disputed", sa.Boolean(), nullable=False),
        sa.Column("ai_confidence", sa.Float(), nullable=False),
        sa.Column("human_reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extracted_facts_case_id"), "extracted_facts", ["case_id"], unique=False
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parties_case_id"), "parties", ["case_id"], unique=False)
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("event_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("significance", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timeline_events_case_id"), "timeline_events", ["case_id"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("overall_strength", sa.Integer(), nullable=False),
        sa.Column("strengths", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weaknesses", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("risk_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recommendations", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_case_id"), "assessments", ["case_id"], unique=False
    )
    op.create_table(
        "contradictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("fact_a_id", sa.Uuid(), nullable=False),
        sa.Column("fact_b_id", sa.Uuid(), nullable=False),
        sa.Column("nature", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("impact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_a_id"],
            ["extracted_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_b_id"],
            ["extracted_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contradictions_case_id"), "contradictions", ["case_id"], unique=False
    )
    op.create_table(
        "evidence_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=False),
        sa.Column("relationship", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight_score", sa.Integer(), nullable=False),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["extracted_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_contradictions_case_id"), table_name="contradictions")
    op.drop_table("contradictions")
    op.drop_index(op.f("ix_assessments_case_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_timeline_events_case_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_parties_case_id"), table_name="parties")
    op.drop_table("parties")
    op.drop_index(op.f("ix_extracted_facts_case_id"), table_name="extracted_facts")
    op.drop_table("extracted_facts")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_qdrant_document_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_filename"), table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_claims_case_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_cases_user_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_name"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
