"""cases table

Revision ID: 401899bba0f0
Revises: 55ef36b82687
Create Date: 2026-07-04 22:45:20.145804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '401899bba0f0'
down_revision: Union[str, Sequence[str], None] = '55ef36b82687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_id', sa.Integer(), nullable=False))
    op.drop_column('cases', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('cases', 'case_id')
    # ### end Alembic commands ###
