"""cases table

Revision ID: 55ef36b82687
Revises: a17c75df3d10
Create Date: 2026-07-04 14:43:44.011779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55ef36b82687'
down_revision: Union[str, Sequence[str], None] = 'a17c75df3d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claim_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plaintiff_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plaintiff_counsel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('defense_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('defense_counsel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('court', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_name'), 'cases', ['case_name'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_name'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
