"""cases table

Revision ID: ce0ae45f556f
Revises: ca5d582d11b0
Create Date: 2026-07-16 00:47:18.416668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce0ae45f556f'
down_revision: Union[str, Sequence[str], None] = 'ca5d582d11b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('juror_count', sa.Integer(), nullable=False),
    sa.Column('plaintiff_votes', sa.Integer(), nullable=False),
    sa.Column('defense_votes', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('average_damages', sa.Float(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_case_id'), 'simulations', ['case_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('juror_number', sa.Integer(), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_simulation_id'), 'personas', ['simulation_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('damages', sa.Float(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('witness_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_persona_id'), 'votes', ['persona_id'], unique=False)
    op.create_index(op.f('ix_votes_simulation_id'), 'votes', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_simulation_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_persona_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_personas_simulation_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_simulations_case_id'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
